Add Rails-style YAML support to i18n-cli
coverhound/i18n-cli pull request #6
Opened 2017-03-21 18:16 UTC by berfarah

In order to use this with Rails projects, we're adding Rails support to the CLI

2017-03-21 18:17 UTC, berfarah commented
So technically this isn't a 50 line diff - but yarn is half of this PR. :)

2017-03-21 18:21 UTC, berfarah commented
Actually, I hacked in the file extension into this PR. I should probably do more refactoring to properly allow for multiple locales with Rails.

2017-03-21 18:32 UTC, kylealwyn requested changes

2017-03-21 18:32 UTC, kylealwyn commented on i18n-1490118652166.csv
> +"bundle","key","en-US"
what's this guy doing in here?

2017-03-21 18:32 UTC, kylealwyn commented on src/commands/bundles.js
>    const bundleList = (files || []).map((file) => (
can remove `(files || [])`

2017-03-21 18:32 UTC, kylealwyn commented on src/adapters/rails.js
> +  extension: '.en.yml',
should be `.lang.yml`, no?

2017-03-21 18:32 UTC, kylealwyn commented on test/adapters/rails.spec.js
> +        expect(object).to.eql({ foo: 'bar' })
why don't i get the full lang object back?

2017-03-21 18:33 UTC, berfarah commented on i18n-1490118652166.csv
> +"bundle","key","en-US"
Oh whoops - thanks.

2017-03-21 18:33 UTC, berfarah commented on src/commands/bundles.js
>    const bundleList = (files || []).map((file) => (
Yep!

2017-03-21 18:34 UTC, berfarah commented on src/adapters/rails.js
> +  extension: '.en.yml',
For rails, no. Unless lang is dynamically replaced?

2017-03-21 18:34 UTC, berfarah commented on test/adapters/rails.spec.js
> +        expect(object).to.eql({ foo: 'bar' })
For spreadsheet upload/diffing we don't want the full lang object.

2017-03-21 18:49 UTC, kylealwyn commented on src/adapters/rails.js
> +  extension: '.en.yml',
just read up on rails i18n. got it.

2017-03-21 20:54 UTC, berfarah commented on src/adapters/rails.js
> +  extension: '.en.yml',
But I feel like it should be possible to replace this :\ I'm don't feel good about making the extension a function for everything though. ill think more about it.

2017-03-21 22:35 UTC, kylealwyn approved these changes
⭐️

2017-03-22 01:51 UTC, merged

2017-03-22 01:52 UTC, berfarah commented
@kylealwyn Can you release this to our NPM? I don't currently know how. Or we can do it together tomorrow :)

2017-03-22 05:55 UTC, kylealwyn commented
Yep! I'll show ya tomorrow